
export interface ConditionContext {
  idade: number;
  sexo: string;
  orientacao: string;
  classe: string;
  regiao: string;
  capital: boolean;
  trabalha: boolean;
  estuda: boolean;
  estagio: boolean;
  aposentado: boolean;
  estresse: boolean;
  estresseHard: boolean;
  remoto: boolean;
  climaFrio: boolean;
  ansiedade: boolean;
  alternativo: boolean;
  escritorio: boolean;
  industriaOuMusica: boolean;
  sobrepeso: boolean;
  abaixoDoPeso: boolean;
  pesoIdeal: boolean;
  obesidadeI: boolean;
  obesidadeII: boolean;
  obesidadeIII: boolean;
  falsoSaudavel: boolean;
  cargosAltos: boolean;
  cafeina: boolean;
  alcoolOuObesidade: boolean;
  alcoolico: boolean;
  desempregado: boolean;
  braçalOuSentado: boolean;
  diabetico: boolean;
  midia: boolean;
  fumante: boolean;
  aco: boolean;
  baixaRenda: boolean;
  gayCis: boolean;
  proSe: boolean;
  drogasInjetaveis: boolean;
  traumaArquivado: boolean;
  hipertenso: boolean;
  traumaInfancia: boolean;
  militarPolicia: boolean;
  vitimaCrime: boolean;
  hipertensoFumante: boolean;
  negroPardo: boolean;
  indigena?: boolean;
  abusoHistorico: boolean;
  historicoDepressivo: boolean;
  desempregoLongo: boolean;
  corporativoEstresse: boolean;
  lutoRecente: boolean;
  obesoFumante: boolean;
  caucasiano: boolean;
  abusoInfanciaProlongado: boolean;
  diabeticoOuHipertenso: boolean;
  isolamentoTotal: boolean;
  falenciaLuto: boolean;
  infartoPrevio: boolean;
  drogasPesadas: boolean;
  fumanteQuimico: boolean;
  atletaMilitar: boolean;
  trabalhadorNuclear: boolean;
  baixaSaudeMental: boolean;
  intoxicacaoMedicamentosa: boolean;
  biotipoAnomalia: string;
  massaMagra: boolean;
  tecnologia: boolean;
  setor: string;
  estado: string;
  geneticaFamiliar: boolean;
  braçal: boolean;
  sop: boolean;
  peleClara: boolean;
  tdah: boolean;
  insonia: boolean;
  turnosNoturnos: boolean;
  idoso: boolean;
  botox: boolean;
  lutador: boolean;
  violencia: boolean;
  lutoSevero: boolean;
  obeso: boolean;
  corticoides: boolean;
  exPresidiario: boolean;
  gangue: boolean;
  corporativo: boolean;
  autoimune: boolean;
  sedentario: boolean;
  trabalhoRisco: boolean;
  alcoolicoAbstinencia: boolean;
  fogo: boolean;
  hepatite: boolean;
  miopiaCongenita: boolean;
  fumantePesado: boolean;
  professorCantor: boolean;
  acidenteTransito: boolean;
  doencaPulmonarCoracao: boolean;
  ensolarado: boolean;
  moradorRua: boolean;
  dependenteQuimicoAtivo: boolean;
  trabalhoBarulhento: boolean;
  acidenteMotorLesao: boolean;
  baixaIodo: boolean;
  diabeticoLesaoPe: boolean;
  colesterolAlto: boolean;
  zonaRuralRemota: boolean;
  herniaDisco: boolean;
  internacaoUTI: boolean;
  mausHabitos: boolean;
  traumaViolento: boolean;
  interrogatorioIntimidacao: boolean;
  quimioterapia: boolean;
  avcExtenso: boolean;
  glaucoma: boolean;
  cancerLaringe: boolean;
  retinopatia: boolean;
  cancerMama: boolean;
  cancerMamaMetastatico: boolean;
  cancerProstataMetastatico: boolean;
  posBariatrica: boolean;
  depressaoProfunda: boolean;
  cancerIntestinalCrohn: boolean;
  zonaTropical: boolean;
  escleroseMultipla: boolean;
  tumorHipofisario: boolean;
  transtornoBorderlineDepressao: boolean;
  anorexiaContext: boolean;
  neurologico: boolean;
  veteranoGuerra: boolean;
  explosao: boolean;
  bombeiro: boolean;
  traumaGrave: boolean;
  catarataContext: boolean;
  endemiaRural: boolean;
  compulsaoTrauma: boolean;
  duchenneContext: boolean;
  talidomidaContext: boolean;
  mergulhoVelocidade: boolean;
  lesaoTronco: boolean;
  sepse: boolean;
  marginalizado: boolean;
  cancerPeleNaoTratado: boolean;
  sobreviventeDesastre: boolean;
  ruinaFinanceira: boolean;
  protecaoTestemunha: boolean;
  paranoiaFortuna: boolean;
  comaPosAcidente: boolean;
  incestoAbuso: boolean;
  incestoConsentido: boolean;
  matouAlguem: boolean;
  exDetento: boolean;
  abandonadoAltar: boolean;
  segundaFamiliaConjuge: boolean;
  filhoFugiu: boolean;
  trocadoMaternidade: boolean;
  casamentoInteressePaixao: boolean;
  expulsaGravidez: boolean;
  criouFilhoAmigo: boolean;
  escolhaFamiliarPerigo: boolean;
  irmaoGemeoAdotado: boolean;
  guardaIrmaosPrisaoPais: boolean;
  alergiaSolar: boolean;
  perdeuMembroAcidente: boolean;
  amnesiaRetrografa: boolean;
  catalepsiaCronica: boolean;
  paraplegiaEsporte: boolean;
  mutacoesCobaia: boolean;
  anacusiaTotal: boolean;
  transplanteCoracaoCriminoso: boolean;
  ataqueAnimalSelvagem: boolean;
  erroMedicoGrosseiro: boolean;
  refemAssalto: boolean;
  acusadoFalsamente: boolean;
  casaInvadida: boolean;
  acidenteFatalPedestre: boolean;
  testemunhouQuedaAviao: boolean;
  seitaExtremistaAbusiva: boolean;
  vitimaStalker: boolean;
  saberCrimeFamoso: boolean;
  falenciaEmpresaFamilia: boolean;
  piramideFinanceira: boolean;
  demissaoHumilhante: boolean;
  vendeuPatenteBarato: boolean;
  vicioJogoPerdaCasa: boolean;
  traicaoSocioDivida: boolean;
  doouPatrimonioFarsa: boolean;
  malaDinheiroSujo: boolean;
  ataqueHackerZerouContas: boolean;
  obraArteDestruida: boolean;
  restosMortaisQuintal: boolean;
  herancaDesconhecido: boolean;
  herdeiroImperioCriminoso: boolean;
  naufragioDeriva: boolean;
  atingidoRaio: boolean;
  carroEsmagadoCarreta: boolean;
  canceladoInternet: boolean;
  isolamentoRemoto: boolean;
  deportadoErroBurocratico: boolean;
  heroiAnonimo: boolean;
  paiMorto: boolean;
  maeMorta: boolean;
  relacaoPositiva: boolean;
  relacaoNeutra: boolean;
  relacaoNegativa: boolean;
  temFilhos: boolean;
  doouOrgaoVital?: boolean;
  exMilitarDesertor?: boolean;
  vingativo?: boolean;
  imigranteRefugiado?: boolean;
  altruista?: boolean;
  exposicaoPublica?: boolean;
  fobiaSocial?: boolean;
  tdahLeve?: boolean;
  tdahModerado?: boolean;
  tdahGrave?: boolean;
  historicoFamiliarNeurodivergente?: boolean;
  estresseCronico?: boolean;
  agorafobia?: boolean;
  nerd?: boolean;
  depressao?: boolean;
  vitiligoGeneralizado?: boolean;
  identidadeGenero: string;
  termoIdentidade: string;
  transgenero: boolean;
  vulneravel?: boolean;
  transporte: string;
  habitacao: string;
  profissao: string;
  classeSocial?: string;
  locomocaoComprometida?: boolean;
  tierMetropole: 'tier_alfa' | 'tier_beta' | 'tier_gama' | 'interior_alfa' | 'interior_beta' | 'interior_gama';
}

export interface CharacterCondition {
  name: string;
  weight: (ctx: ConditionContext) => number;
}

export interface ShinyEvent {
  text: string;
  condition?: (ctx: ConditionContext) => boolean;
  weight: (ctx: ConditionContext) => number;
}

export interface GenerationOptions {
  fixedAge?: number;
  fixedBioSex?: 'Masculino' | 'Feminino';
  fixedTrans?: boolean;
  minVisibleLevel?: number;
  minNonVisibleLevel?: number;
  forceUnemployed?: boolean;
  fixedClass?: string;
  fixedRegion?: 'Sul' | 'Norte' | 'Nordeste' | 'Sudeste' | 'Centro-Oeste';
  fixedIdentityTerm?: string;
  fixedCondition?: string;
  fixedShiny?: string;
  fixedLocality?: 'Capital' | 'Interior';
  fixedEthnicity?: string;
  fixedManualLabor?: boolean;
  fixedRemoteArea?: boolean;
  fixedAnxiety?: boolean;
  fixedStress?: boolean;
  fixedRelational?: string[];
  fixedFilhos?: string[];
}

export interface ProbData {
  prob: number;
  poolSize?: number;
}

export interface CharacterResult {
  text: string;
  metadata: {
    nome: string; idade: number; genero: string; bioSex: string; etnia: string; orientacao: string; classe: string; regiao: string; perfilUrbano: string; profissao: string; statusOcupacional: string; vConditions: string[]; nvConditions: string[]; habitacao: string; transporte: string; resiliencia: string; temperamento: string; shiny: string; cenaSexualidade: string; fetiches: string[]; triboUrbana: string; rastro: string; biotipo: string; biotipoAnomalia: string; altura: number; peso: number; imc: number; massaMagra: boolean; photos: string[]; baggage: { type: string, text: string, prob?: ProbData, isMigrated?: boolean }[];
    metrics: { physical: number; mental: number; income: number; relational: number; resilience: number; urbanLife: number; };
    probs: Record<string, ProbData | ProbData[]>;
    friccaoUrbana: string;
    migratedItems: string[];
    bodyMap?: { id: string, color: string }[];
  }
}
